package com.eyespynature.client;

public enum HistoryTokenType {
	RESTORE_PRODUCT, MANAGE_STOCK, UPDATE_PRODUCT, OBSOLETE_PRODUCT, MANAGE_FILES, ADD_PRODUCT, MANAGE_ORDERS, PRODUCT_HTML, OTHER_HTML, UPDATE_ONE_PRODUCT
}